---
- name: check if clamav is installed
  stat:
    path: /usr/bin/clamav
  register: clam_bin
  #- name: install freshclam
  #  yum:
  #    name: clamav-update
  #    state: installed
  #  when: clam_bin.stat.exists
  #  tags:
  #    - build_image
- name: 'systemd slices (cgroup limits), timers, and service units'
  template:
    dest: /etc/systemd/system/
    src: "{{ unit_file }}"
    mode: "0644"
    setype: etc_t
    owner: "root"
    group: "root"
  loop:
    - 'freshclam.service'
    - 'clamscan.service'
    - 'clam.slice'
    - 'freshclam.timer'
    - 'clamscan.timer'
  loop_control:
    loop_var: unit_file
- name: 'clam config'
  template:
    dest: "/etc/clamd.d/scan.conf"
    src: clam.d_scan.conf
    mode: "0644"
    owner: "root"
    group: "root"
  tags:
    - build_image
- name: 'freshclam (clamav defination downloader) config'
  template:
    dest: /etc/clamd.d/
    src: freshclam.conf
    mode: "0644"
    owner: "root"
- name: 'enable clam services'
  systemd:
    name: "{{ unit }}"
    enabled: yes
    state: restarted
  loop:
    - 'freshclam.service'
    - 'clamscan.service'
    - 'freshclam.timer'
    - 'clamscan.timer'
  loop_control:
    loop_var: unit
