---
# tasks file for common Linux machines
- name: set pki location, it seems that the accepted standard is /etc/ssl/, but sometime early on there was a question posed to a mailing list and /etc/pki was born
  set_fact:
    filesystem_pki: "{{ prepath }}{% if ansible_facts.os_family == 'RedHat' %}/etc/pki/ca-trust/source/anchors/{% elif ansible_facts.os_family == 'Debian' %}/usr/local/share/ca-certificates/{% endif %}"
    system_bashrc: "{{ ( ansible_facts.os_family == 'Debian' ) | ternary('bash.bashrc', 'bashrc') }}"
    sshd_config: "{{ ( ansible_facts.os_family == 'Debian' ) | ternary('sshd.config', 'sshd_config') }}" 

- name: import certificates from variable
  copy:
    content: "{{ item.value }}"
    dest: "{{ filesystem_pki }}{{ item.key }}.crt"
    mode: 0664
    owner: root
    group: root
    setype: cert_t
    validate: "openssl x509 -in %s"
  loop: "{{ trusted_ca_map |  default({}) | dict2items }}"
  register: cert_map
  tags:
    - chroot

- name: transfer certificates to trust directory
  copy:
    src: "{{ item }}"
    dest: "{{ filesystem_pki }}{{ item }}"
    mode: '0664'
    owner: root
    group: root
    setype: cert_t
    validate: "openssl x509 -in %s"
  loop: "{{ trusted_ca_file_list }}"
  when: trusted_ca_file_list is defined
  tags:
    - chroot
##### BEGIN OS Packaging and Repositories #####
- name: initial redhat distribution specific block
  block:
    - name: typically redhat method
      command: update-ca-trust force-enable
      when: cert_map.changed

    - name: package manager related tasks
      include_tasks: rpm.yml
      when: repo_criteria is defined
      tags:
        - chroot
  when: ansible_facts.os_family == 'RedHat' or ansible_os_family == 'Archlinux'

- name: initial debian distribution specific block
  block:
    - name: typically debian method
      command: update-ca-certificates
      when: cert_map.changed
    - name: package manager related tasks
      include_tasks: apt.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Suse'

- name: primary
  include_tasks: base.yml
