---
# tasks file for common Linux machines
- name: primary
  include_tasks: base.yml
- name: clamAV configure
  include_tasks: clamav.yml
- name: basic automation group
  include_tasks: system_groups.yml
  
