---
- name: 'priority package update, patches security related concerns quickly'
  yum:
    security: yes
    state: latest
    update_cache: yes
  register: updated_packages
- name: 'create map of updated packages and their files'
  set_fact: "{{ updated_files | default({}) | combine( { item:  | basename } ) }}"
  with_items: "{{ updated_packages }}"

- name: 'check if any packages that were updated are running'
  shell: "lsof -nP +L1 | awk '{print $10}'"
  register: lsof_deleted
- name: 'rpm query for the files'
  command: rpm -qf {{ item }} 
  register: packages_running_with_deleted_files
  loop: "{{ packages_running_with_deleted_files.stdout.split('\n') }}"
- name: 'query packages for systemd units that could be restarted'
  shell: grep -oP '(/usr/lib/systemd/system/)\K\w.*'
  register: potentially_restartable
  
#https://blog.habets.se/2011/07/OpenSSH-certificates.html
var:
    message: |
            Right now the gpg key is unprotected, you can change that by changing the key's password by using `gpg2 --edit-key {{ user.gpg_id }} < passwd` then save



