---
#- name: 'let sysadm_r (devops/power-users) login with ssh'
#  seboolean:
#    name: ssh_sysadm_login
#    state: yes
#    persistent: yes
#- name: 'set selinux context on container dir' 
  #/srv/containers(/.*)?                      system_u:object_r:svirt_sandbox_file_t
- name: relabel almost the full filesystem
  command: restorecon -Rv /var /usr /etc /opt /srv /bin /lib /sbin

