--- 
- name: 'let sysadm_r (devops) login with ssh'
  seboolean:
    name: ssh_sysadm_login
    state: yes
    persistent: yes
#- name: 'set selinux context on container dir' 
  #/var/log/audit(/.*)?                      system_u:object_r:svirt_sandbox_file_t
- name: relabel
  command: restorecon -Rv /

