---
- name: if argument is passed, add it
  set_fact:
    revoked_users: "{{ revoked_users | combine(revoked_user: 'purge') }}"
  when: revoked_user is defined

- name: new kill
  command: "pkill --signal 9 -U {{ u.key }}"
  ignore_errors: true
  loop: "{{ revoked_users |dict2items }}"
  when: u.value != 'soft'
  loop_control:
    loop_var: u

- name: archive user contents
  command: "tar czf userhome_{{ u.key }}_archive.tar.gz /home/{{ u.key }}"
  when: ( users[u.key]['archive_home'] is defined and users[u.key]['archive_home'] |bool == True) or (u.value == 'archive' )
  loop: "{{ revoked_users |dict2items }}"
  loop_control:
    loop_var: u

- name: remove user
  user:
    name: "{{ u.key }}"
    state: absent
  when: (revoked_users is defined) and (revoked_users |length >= 1)
  loop: "{{ revoked_users |dict2items }}"
  loop_control:
    loop_var: u
