---
- name: new kill
  command: "pkill --signal 9 -U {{ item }}"
  ignore_errors: true
#- name: archive user contents
#  command: "tar czf userhome_{{ item }}_archive.tar.gz /home/{{ item }}"
#  when: "{{ users[item].archive_home|bool}}"
#  loop: "{{ revoked_users }}"
- name: remove user
  user:
    name: "{{ u }}"
    state: absent
  loop: "{{ revoked_users }}"
  loop_control:
    loop_var: u
