---
# tasks file for users
- name: 'modify group membership'
  group:
    name: "{{ g.name }}"
    state: present
    gid: "{{ g.gid }}"
  loop: "{{ user_groups }}"
  loop_control:
    loop_var: g
  tags:
    - groupadd
- name: add the user
  block:
  - name: 'add users'
    user:
      name: "{{ u.name }}"
      uid: "{{ u.uid }}"
      comment: "{{ u.comment }}"
      state: present
      seuser: "{{ u.selinux }}"
      groups: "{{ u.primary_group }}"
    loop: "{{ user_map }}"
    loop_control:
      loop_var: u
    tags:
      - useradd
  - name: 'auth_key module '
    authorized_key:
      user: "{{ u.name }}"
      key: "{{ u.public_keys[0] }}"
    when: "u.public_keys[0] | length >= 1"
    loop: "{{ user_map }}"
    loop_control:
      loop_var: u
    tags:
      - useradd
      - authorized_keys
      - core-preview
- template:
    dest: "/etc/sudoers.d/{{ g.name }}"
    src: sudo_group.j2
    mode: '0400'
    owner: 'root'
    group: 'root'
    validate: '/usr/sbin/visudo -cf %s'
  loop: "{{ user_groups }}"
  loop_control:
    loop_var: g
  tags:
    - sudo
    - groupadd
