# TODO, this will help allow adding local users on a central server, this might only be needed when operators don't have Individual Linux machines to work on
- name: skel create ssh config for our domain customizations, for new accounts
  copy:
    owner: root
    group: root
    mode: 0600
    dest: "/etc/skel/.ssh/config.d/{{ domain }}"
    content: |
      ControlMaster auto
      ControlPath ~/.ssh/sockets/C_%h 
      ControlPersist 6h
      Compression yes
      ForwardAgent yes
      RemoteForward .gnupg/S.gpg-agent.extra .gnupg/S.gpg-agent.forward
      Include ~/.ssh/config.d/*conf
- name: skel create ssh config, for new accounts
  copy:
    owner: root
    group: root
    mode: 0600
    dest: /etc/skel/.ssh/config
    content: |
      Host *.{{ domain }}
      HostKeyAlgorithms ssh-dss-cert-v01@openssh.com,ssh-dss
      Host bastion-jump
      Port 22223
      DynamicForward localhost:9119
      LocalForward 9117 localhost:9117
      ProxyCommand ssh {{ bastion-jump-host }} -W %h:%p -q
- name: skel create .vimrc, for new accounts
  copy:
    owner: root
    group: root
    mode: 0644
    dest: /etc/skel/.ssh/known_hosts
    content: |
      @cert-authority {{ ssh_host_ca_pub }}

- name: 'home files'
  copy:
    owner: "{{ item.0 }}"
    content: "{{ item.1.files }}"
  loop: "{{ files | subelements('files') }}"
- name: 'create 2fa file'
  template:
    path: /etc/users-hotp
    owner: 'root'
    group: 'root'
  loop: "{{ users }}"
