---
# tasks file for users
- name: 'modify group membership'
  group:
    name: "{{ g.name }}"
    state: present
    gid: "{{ g.gid }}"
  loop: "{{ user_groups }}"
  loop_control:
    loop_var: g
  tags:
    - groupadd
- name: add the user
  block:
  - name: 'add users'
    user:
      name: "{{ u.name }}"
      uid: "{{ u.uid }}"
      comment: "{{ u.comment }}"
      state: present
      seuser: "{{ u.selinux }}"
      groups: "{{ u.primary_group }}"
    loop: "{{ user_map }}"
    loop_control:
      loop_var: u
    tags:
      - useradd
  - name: 'print'
    debug:
      msg: "{{ u.0 }} and pub {{ u.1 }}"
    loop: "{{ user_map |subelements('public_keys') }}"
    loop_control:
      loop_var: u

  - name: 'auth_key module '
    authorized_key:
      user: "{{ u.0.name }}"
      key: "{{ u.1 }}"
    when: u | length >= 1
    loop: "{{ user_map |subelements('public_keys') }}"
    loop_control:
      loop_var: u
    tags:
      - useradd
      - authorized_keys
      - core-preview
