---
- name: prepare
  hosts: all
  tasks:
    - name: update apt manually
      command:
        cmd: apt-get update
      register: apt_updated
      when: ansible_facts['os_family'] == 'Debian'

    - name: install python-apt
      command:
        cmd: apt-get -y install python3-apt
      when: ansible_facts['os_family'] == 'Debian'

    - name: install items that are usually missing in containers
      package:
        name: "{{ item }}"
      loop:
        - rsyslog
        - openssl
        - openssh-server
        - tzdata
        - grub2
    
