users:
 - default
disable_root: 1
ssh_pwauth:   0
mount_default_fields: [~, ~, 'auto', 'defaults,nofail', '0', '2']
resize_rootfs_tmp: /dev
ssh_svcname: sshd
ssh_deletekeys:  0
ssh_genkeytypes:  [ 'ed25519' ]
syslog_fix_perms: ~
preserve_hostname: true
cloud_init_modules:
 - migrator
 - bootcmd
 - write-files
 - growpart
 - disk_setup
 - resizefs
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - rsyslog
 - users-groups
 - ssh
cloud_config_modules:
 - mounts
 - locale
 - set-passwords
{% if ansible_os_family == 'RedHat' %}
 - yum-add-repo
{% endif %}
 - package-update-upgrade-install
 - timezone
{% if machine_type != aws %}
 - disable-ec2-metadata
{% endif %}
 - runcmd
cloud_final_modules:
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - phone-home
 - final-message
system_info:
  default_user:
    name: autobot
    lock_passwd: true
    gecos: Unified Automation User
    groups: [wheel, adm, systemd-journal]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
  paths:
    cloud_dir: /var/lib/cloud
    templates_dir: /etc/cloud/templates
  ssh_svcname: sshd
write_files:
    - path: "/etc/docker/daemon.json"
      owner: "root:root"
      content: |
        {
          "labels": [ "os=linux", "arch=amd64" ],
          "experimental": true
        }
mounts:
 - [ ephemeral0, /media/ephemeral0 ]
 - [ ephemeral1, /media/ephemeral1 ]
 - [ swap, none, swap, sw, "0", "0" ]
# vim:syntax=yaml

